// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "01-cours" }],
  labos : [{type: "autogenerated", dirName:"02-labos"}],
  tp: [{ type: "autogenerated", dirName: "03-tp" }],
};

module.exports = sidebars;
