// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    { type: "doc", id: "cours/rencontre1", label: "Rencontre 1 — Environnement et HTML" },
    { type: "doc", id: "cours/rencontre2", label: "Rencontre 2 — HTML, fichiers et navigation" },
    { type: "doc", id: "cours/rencontre3", label: "Rencontre 3 — Introduction à CSS" },
    { type: "doc", id: "cours/rencontre4", label: "Rencontre 4 — Modèle en boîte et espacements" },
    { type: "doc", id: "cours/rencontre5", label: "Rencontre 5 — Flexbox simple et intégration" },
    { type: "doc", id: "cours/rencontre6", label: "Rencontre 6 — Variables et JavaScript" },
    { type: "doc", id: "cours/rencontre7", label: "Rencontre 7 — Conditions et logique" },
    { type: "doc", id: "cours/rencontre8", label: "Rencontre 8 — Fonctions" },
    { type: "doc", id: "cours/rencontre9", label: "Rencontre 9 — DOM de base" },
    { type: "doc", id: "cours/rencontre10", label: "Rencontre 10 — Événements et classes CSS" },
    { type: "doc", id: "cours/rencontre11", label: "Rencontre 11 — Boucles" },
    { type: "doc", id: "cours/rencontre12", label: "Rencontre 12 — Tableaux" },
    { type: "doc", id: "cours/rencontre13", label: "Rencontre 13 — Plusieurs éléments du DOM" },
    { type: "doc", id: "cours/rencontre14", label: "Rencontre 14 — Rattrapage et révision" },
    { type: "doc", id: "cours/rencontre15", label: "Rencontre 15 — Évaluation sommative finale" },
  ],
  labos: [{ type: "autogenerated", dirName: "02-labos" }],
};

module.exports = sidebars;
